config/routes.rb
Rails.application.routes.draw do
  
  resources :curriculums

  resources :cvs

  get 'home', to: 'pages#home'
  get 'portfolio', to: 'pages#portfolio'
  get 'open_source', to: 'pages#open_source'
  get 'blog', to: 'pages#blog'
  
  get 'contact', to: 'pages#contact'
  post 'contact', to: 'pages#send_contact_mail'
  get 'thanks', to: 'pages#thanks'
  get 'web_design', to: 'pages#web_design'
  get 'game_development', to: 'pages#game_development'
  get 'wd_project', to: 'pages#wd_project'
  get 'pricing', to: 'pages#pricing'
  get 'post', to: 'pages#blog'
  get 'pipecvs', to: 'pages#cvs_page'
  
  get 'curriculums', to: 'curriculums#index'


  # You can have the root of your site routed with "root"
   root 'pages#home'
end

app/models/curriculum.rb
class Curriculum
  include Mongoid::Document
  store_in database: "timba_development"

  embeds_many :languages
  accepts_nested_attributes_for :languages

  embeds_many :educations
  accepts_nested_attributes_for :educations

  embeds_many :work_experiences
  accepts_nested_attributes_for :work_experiences


  field :first_name, type: String
#  validates :full_name	, presence: true, length: { minimum: 5 }
  
  field :last_name, type: String

  field :country, type: String

  field :profile, type: String
#  validates :profile , presence: true, length: { maximum: 100 }

  field :experience, type: Integer
#  validates :experience , presence: true, length: { minimum: 1 } && { maximum:2 }

  field :availability, type: String

  field :preferred_environment, type: String

  #field :recent_work_experience, type: Array

  field :skills, type: Array

  def string_to_array(source)
    source.split(',').map { |v| v.strip }
  end

  def array_to_string(source)
    if source != nil
      source.join(', ')
    end
  end

  def skills_list=(arg)
    self.skills = string_to_array(arg)
  end

  def skills_list
    array_to_string(self.skills)
  end

  def recent_work_experience_list=(arg)
    self.recent_work_experience = string_to_array(arg)
  end

  def recent_work_experience_list
    array_to_string(self.recent_work_experience)
  end
end

class Language
  include Mongoid::Document
  field :name, type: String
  field :proeficiency, type: Integer
  embedded_in :curriculum
end

class Education
  include Mongoid::Document
  field :institution, type: String
  field :carreer, type: String
  embedded_in :curriculum
end

class WorkExperience
  include Mongoid::Document
  field :company, type: String
  field :job, type: String
  field :time, type: Integer
  embedded_in :curriculum
end

app/models/cv.rb
class Cv
  include Mongoid::Document
  store_in database: "timba_development"

  field :full_name, type: String
#  validates :full_name	, presence: true, length: { minimum: 5 }

#  field :profile, type: String
#  validates :profile , presence: true, length: { maximum: 50 }

#  field :experience, type: Integer
#  validates :experience , presence: true, length: { minimum: 1 } && { maximum:2 }

#  field :recent_work_experience, type: Array

#  field :skills, type: Array

#  field :education, type: Array
  
#  field :languages, type: Array

end

app/controllers/curriculums_controller.rb
class CurriculumsController < ApplicationController
  before_action :set_curriculum, only: [:show, :edit, :update, :destroy]

  # GET /curriculums
  # GET /curriculums.json
  def index
    @curriculums = Curriculum.all
  end

  # GET /curriculums/1
  # GET /curriculums/1.json
  def show
  end

  # GET /curriculums/new
  def new
    @curriculum = Curriculum.new
    @curriculum.languages << Language.new 
    @curriculum.languages << Language.new
    @curriculum.educations << Education.new
    @curriculum.educations << Education.new
    @curriculum.work_experiences << WorkExperience.new
    @curriculum.work_experiences << WorkExperience.new
  end

  # GET /curriculums/1/edit
  def edit
  end

  # POST /curriculums
  # POST /curriculums.json
  def create
    @curriculum = Curriculum.new(curriculum_params)

    respond_to do |format|
      if @curriculum.save
        format.html { redirect_to @curriculum, notice: 'Curriculum was successfully created.' }
        format.json { render :show, status: :created, location: @curriculum }
      else
        format.html { render :new }
        format.json { render json: @curriculum.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /curriculums/1
  # PATCH/PUT /curriculums/1.json
  def update
    respond_to do |format|
      if @curriculum.update(curriculum_params)
        format.html { redirect_to @curriculum, notice: 'Curriculum was successfully updated.' }
        format.json { render :show, status: :ok, location: @curriculum }
      else
        format.html { render :edit }
        format.json { render json: @curriculum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /curriculums/1
  # DELETE /curriculums/1.json
  def destroy
    @curriculum.destroy
    respond_to do |format|
      format.html { redirect_to curriculums_url, notice: 'Curriculum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curriculum
      @curriculum = Curriculum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def curriculum_params
      params.require(:curriculum).permit(:first_name, :last_name, :country, :profile, 
        :experience, :availability, :preferred_environment, :skills_list,
        languages_attributes: [:id, :name, :proeficiency], educations_attributes: [:id,
         :institution, :carreer], work_experiences_attributes: [:id, :company, :job, :time])
    end
end

app/controllers/cvs_controller.rb
class CvsController < ApplicationController
  before_action :set_cv, only: [:show, :edit, :update, :destroy]

  # GET /add_cvs
  # GET /add_cvs.json
  def index
    @cvs = Cv.all
  end

  # GET /add_cvs/1
  # GET /add_cvs/1.json
  def show
  end

  # GET /add_cvs/new
  def new
    @cv = Cv.new
  end

  # GET /add_cvs/1/edit
  def edit
  end

  # POST /add_cvs
  # POST /add_cvs.json
  def create
    @cv = Cv.new(cv_params)

    respond_to do |format|
      if @cv.save
        format.html { redirect_to @cv, notice: 'Cv was successfully created.' }
        format.json { render :show, status: :created, location: @cv }
      else
        format.html { render :new }
        format.json { render json: @cv.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /add_cvs/1
  # PATCH/PUT /add_cvs/1.json
  def update
    respond_to do |format|
      if @cv.update(cv_params)
        format.html { redirect_to @cv, notice: 'Cv was successfully updated.' }
        format.json { render :show, status: :ok, location: @cv }
      else
        format.html { render :edit }
        format.json { render json: @cv.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /add_cvs/1
  # DELETE /add_cvs/1.json
  def destroy
    @cv.destroy
    respond_to do |format|
      format.html { redirect_to cvs_url, notice: 'Cv was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cv
      @cv = Cv.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cv_params
      params.require(:cv).permit(:full_name, :profile, :experience, :recent_work_experience, :skills, :education, :languages)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	
  def home
  end

  def open_source
  end
  
  def blog
  end

  def portfolio
  end

  def contact
  end

  def thanks
  end

  def web_design
  end

  def game_development
  end
 

	def send_contact_mail
		name = params[:name]
		mail = params[:email]
		message = params[:message]
		ContactUsMailer.contact_us_email(name, mail, message).deliver
    redirect_to :thanks
  end
end

app/helpers/add_cvs_helper.rb
module AddCvsHelper
end

app/helpers/curriculums_helper.rb
module CurriculumsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/curriculums/_form.html.erb
<section class="section swatch-beige-black new">
  <%= form_for(@curriculum) do |f| %>
    <% if @curriculum.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@curriculum.errors.count, "error") %> prohibited this curriculum from being saved:</h2>

        <ul>
          <% @curriculum.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <div class="col-md-3 col-md-offset-1">
        <a class="logo" href="/home">
          <br>
          <img class="img-rounded" src="<%=image_path("design/people/user.png")%>" alt="a clock">
        </a>
      </div>

      <div class="col-md-7 info"><br>
        <div class="field name"><%= f.label :first_name %><br><%= f.text_field :first_name %></div><p></p>
        <div class="field name"><%= f.label :last_name %><br><%= f.text_field :last_name %></div><p></p>

        <div class="country"><div class="field"><b><%= f.label :country %></b><br><%= f.text_field :country %></div></div><p></p>
        <div class="member_info"><div class="field profile"><b><%= f.label :profile %></b><br><%= f.text_area :profile %></div><br></div>
        <ul class="detalles">     
          <li><a class="btn btn-default" href="home" role="button">Objetive C</a></li>
          <li><a class="btn btn-default" href="home" role="button">IOS</a></li>
          <li><a class="btn btn-default" href="home" role="button">SQL</a></li>
          <li><a class="btn btn-default" href="home" role="button">C++</a></li>
          <li><a class="btn btn-default" href="home" role="button">Java</a></li>
          <li><a class="btn btn-default" href="home" role="button">Cocoa Touch</a></li>
          <li><a class="btn btn-default" href="home" role="button">Aplle Xcode</a></li>
          <li><a class="btn btn-default" href="home" role="button">HTML5</a></li>
          <li><a class="btn btn-default" href="home" role="button">Show More</a></li>
        </ul>
      </div>  
    </div><br>

    <hr class="linea" align="center" width="90%">

    <div class="row">
      <div class="col-md-3 col-md-offset-1 characters"><br>
        <div class="titulo"><strong>PORTFOLIO:</strong></div>
        <ul>
          <li><a href="home"><b>Life360 (via toptal)</b></a>
            <p>iOS</p>
          </li>
          <li><a href="home"><b>Software Factory LLC</b></a>
            <p>iOS, Objective-C, CocoaTouch, Xcode</p>
          </li>
          <li><a href="home"><b>IntegraSoft</b></a>
            <p>.NET, SQL, Oracle, HTML, CSS, ASP.NET</p>
          </li>
        </ul>
      </div>
      <div class="col-md-3"><br>
        <div class="titulo"><strong>EXPERIENCE:<b>(years)</b></strong></div>
        <ul>
          <div class="field"><br><%= f.number_field :experience %></div><br>
        </ul>
      </div>
      <div class="col-md-3">
        <a class="logo" href="/home">
          <img class="svg-inject" src="<%=image_path("design/vector/img-1-600x518.png")%>" alt="a clock">
        </a>
      </div><br>
      <hr class="linea" align="center" width="90%">
    </div><br>

    <div class="row segunda">
      <div class="col-md-3 col-md-offset-1 segunda">
        <div class="titulo"><strong>AVAILABILITY:</strong></div>
        <div class="field"><br><%= f.text_field :availability %><br>( Full time, Part time)</div><br>
        <br>
      </div>
      <div class="col-md-3 segunda">
        <div class="titulo"><strong>PREFERRED ENVIRONMENT:</strong></div>
        <div class="field"><br><%= f.text_field :preferred_environment %><br>( Windows, Mac OS, linux)</div><br>
        <br>
      </div>
      <div class="col-md-4">
        <div class="titulo"><strong>LANGUAGES:</strong></div>
      </div>
      <div class="col-md-4">
        <div class="field languages name">
          <%= f.fields_for :languages  do |l| %>
            <%= l.label :name %><br><%= l.text_field :name %><p></p>
            <%= l.label :proeficiency %><br><%= l.number_field :proeficiency %><p></p>
            <br>
          <% end %>
        </div>
      </div>
    </div>

    <div class="row">
      <hr class="linea" align="center" width="90%"><br>
      <div class="col-md-3 col-md-offset-1">
        <div class="titulo"><strong>EMPLOYMENT:</strong></div>
      </div>
      <div class="col-md-7">
        <div class="field employees">
          <%= f.fields_for :work_experiences  do |work| %>
            <%= work.label :company %><br><%= work.text_field :company %><p></p>
            <%= work.label :job %><br><%= work.text_field :job %><p></p>
            <%= work.label :time %>(years)<br><%= work.number_field :time %><p></p>
            <br>
          <% end %>
        </div>
      </div>
    </div>

    <div class="row">
      <hr class="linea" align="center" width="90%"><br>
      <div class="col-md-2 col-md-offset-1">
        <div class="titulo"><strong>SKILLS:</strong></div>
      </div>
      <div class="col-md-7">
        <ul class="subtitulos">
          <ul class="subtitulos">
            <div class="field skills"><%= f.text_area :skills_list %><br>separate with commas</div>
          </ul>
        </ul>
      </div>
    </div>

    <div class="row xtra">
      <hr class="linea" align="center" width="90%"><br>
      <div class="col-md-2 col-md-offset-1">
        <div class="titulo"><strong>EDUCATION:</strong></div>
      </div>
      <div class="col-md-7">
        <ul class="subtitulos">
          <div class="field education">
            <%= f.fields_for :educations  do |ed| %><br>
              <%= ed.label :institution %><br><%= ed.text_field :institution %><p></p>
              <%= ed.label :carreer %><br><%= ed.text_field :carreer %>
              <br>
            <% end %>
          </div>
        </ul>
      </div>
    </div><br><br>

    <div class="actions">
      <button type="button" class="btn btn-default">
        <%= f.submit %>
      </button>
    </div>

    <div class="row footer">
      <div class="col-md-2 col-md-offset-1">
        <a class="logo" href="/home">
          <img class="cabecera" src="<%=image_path("small_timba.png")%>" alt="a clock">
        </a>
      </div>
      <div class="col-md-4">Exclusive access to top developers</div>
      <div class="col-md-3">Timba.co<br>Call us: 888.604.3188</div>
    </div>
    <br>
  <% end %>
</section>

app/views/curriculums/edit.html.erb
<section class="section swatch-black-beige editing">
	<div class="container">
		<h1 class="headline hyper hairline">Editing curriculum</h1>
		<br>
		<%= render 'form' %>
		<br>
		<div class="botones">
			<button type="button" class="btn btn-default"><%= link_to 'Show', @curriculum %></button> |
			<button type="button" class="btn btn-default"><%= link_to 'Back', curriculums_path %></button>
		</div>
	</div>
</section>

app/views/curriculums/index.html.erb
<section class="section swatch-black-beige adding">
  <div class="container">
    <h1 class="headline hyper hairline">Listing curriculums</h1>

    <div class="add">
      <u><%= link_to 'New Curriculum', new_curriculum_path %></u>
    </div><br>

    <table class="table table-striped">
      <thead>
        <tr>
          <th class="prim">Name</th>
          <th>Country</th>
          <th>Experience</th>
          <th>Availability</th>
          <th>Skills</th>
          <th>Languages</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @curriculums.each do |curriculum| %>
        <tr>
          <td><%= curriculum.first_name %>&nbsp;<%= curriculum.last_name %></td>
          <td><%= curriculum.country %></td>
          <td><%= curriculum.experience %></td>
          <td><%= curriculum.availability %></td>
          <td><%= curriculum.skills_list %></td>
          <td><% curriculum.languages.each do |language|%>
                <%= language.name %>&nbsp;
                <%= language.proeficiency %><br>
             <% end %>
          </td>
          
          <p></p>
          <td><%= link_to 'Show', curriculum %></td>
          <td><%= link_to 'Edit', edit_curriculum_path(curriculum) %></td>
          <td><%= link_to 'Destroy', curriculum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <br><br>
</section>

app/views/curriculums/new.html.erb
<section class="section swatch-black-beige new">
	<div class="container">
		<h1>New curriculum</h1>

		<%= render 'form' %>
		<br>
		<div class="bot">
			<button type="button" class="btn btn-default"><%= link_to 'Back', curriculums_path %></button>
		</div>
		<br><br><br><br>
	</div>
</section>

app/views/curriculums/show.html.erb
<div class="cvs"><br>
  <div class="container cvs">
    <section class="section swatch-beige-black">
      
      <div class="row">
        <div class="col-md-3 col-md-offset-1">
          <a class="logo" href="/home">
            <img class="img-rounded" src="<%=image_path("design/people/user.png")%>" alt="a clock">
          </a> 
          <p><a href="/home" type="button" class="btn btn-primary">Hire&nbsp;<%= @curriculum.first_name %></a></p>
        </div>

        <div class="col-md-7 info">
          <h1 class="cv_name"><%= @curriculum.first_name %>&nbsp;<%= @curriculum.last_name %></h1>
          <div class="country"><%= @curriculum.country %></div><p></p>
          <div class="member_info"><%= @curriculum.profile %>
          </div><br>
          <ul class="detalles">     
            <li><a class="btn btn-default" href="/home" role="button">Objetive C</a></li>
            <li><a class="btn btn-default" href="/home" role="button">IOS</a></li>
            <li><a class="btn btn-default" href="/home" role="button">SQL</a></li>
            <li><a class="btn btn-default" href="/home" role="button">C++</a></li>
            <li><a class="btn btn-default" href="/home" role="button">Java</a></li>
            <li><a class="btn btn-default" href="/home" role="button">Cocoa Touch</a></li>
            <li><a class="btn btn-default" href="/home" role="button">Aplle Xcode</a></li>
            <li><a class="btn btn-default" href="/home" role="button">HTML5</a></li>
            <li><a class="btn btn-default" href="/home" role="button">Show More</a></li>
          </ul>
        </div>  
      </div><br>

      <hr class="linea" align="center" width="90%">

      <div class="row">
        <div class="col-md-3 col-md-offset-1 characters"><br>
          <div class="titulo"><strong>PORTFOLIO:</strong></div>
          <ul>
            <li><a href="/home"><b>Life360 (via toptal)</b></a>
              <p>iOS</p>
            </li>
            <li><a href="/home"><b>Software Factory LLC</b></a>
              <p>iOS, Objective-C, CocoaTouch, Xcode</p>
            </li>
            <li><a href="/home"><b>IntegraSoft</b></a>
              <p>.NET, SQL, Oracle, HTML, CSS, ASP.NET</p>
            </li>
          </ul>
        </div>
        <div class="col-md-3"><br>
          <div class="titulo"><strong>EXPERIENCE:</strong></div>
          <ul>
            <b><%= @curriculum.experience %> Years</b>
          </ul>
        </div>
        <div class="col-md-3">
          <a class="logo" href="/home">
            <img class="svg-inject" src="<%=image_path("design/vector/img-1-600x518.png")%>" alt="a clock">
          </a>
        </div><br>
        <hr class="linea" align="center" width="90%">
      </div><br>

      <div class="row segunda">
        <div class="col-md-3 col-md-offset-1 segunda">
          <div class="titulo"><strong>AVAILABILITY:</strong></div>
            <%= @curriculum.availability %>
          <br>
          <br>
        </div>
        <div class="col-md-3 segunda">
          <div class="titulo"><strong>PREFERRED ENVIRONMENT:</strong></div>
            <%= @curriculum.preferred_environment %>
          <br>
          <br>
          <br>
        </div>
        <div class="col-md-3">
          <div class="titulo"><strong>LANGUAGES:</strong></div>
              <% @curriculum.languages.each do |language|%>
                <%= language.name %>&nbsp;  <%= language.proeficiency %><br>
             <% end %>
        </div>
      </div>

      <div class="row">
        <hr class="linea" align="center" width="90%"><br>
        <div class="col-md-2 col-md-offset-1">
          <div class="titulo"><strong>EMPLOYMENT:</strong></div>
          <div class="col-md-3">
            <ul class="subtitulos">
              <ul class="subtitulos">
                <% @curriculum.work_experiences.each do |work_experience|%>
                  <strong><u><%= work_experience.company %></u></strong><br>
                <% end %>
              </ul>
            </ul>
          </div>
        </div>
          <div class="col-md-3">
            <ul class="subtitulos">
              <ul class="subtitulos">
              <br>
                <% @curriculum.work_experiences.each do |work_experience|%>
                  <%= work_experience.job %><br>
                <% end %>
              </ul>
            </ul>
          </div>
          <div class="col-md-2">
            <ul class="subtitulos">
              <ul class="subtitulos">
              <br>
                <% @curriculum.work_experiences.each do |work_experience|%>
                  <%= work_experience.time %>(years)<br>
                <% end %>
              </ul>
            </ul>
          </div>
        </div>
      
        
      <div class="row">
        <hr class="linea" align="center" width="90%"><br>
        <div class="col-md-2 col-md-offset-1">
          <div class="titulo"><strong>SKILLS:</strong></div>
        </div>
        <div class="col-md-7">
          <ul class="subtitulos">
            <ul class="subtitulos">
              <% @curriculum.skills.each do |a| %>
                <li><%= a %></li>
              <% end %>
            </ul>
          </ul>
        </div>
      </div>

      <div class="row">
        <hr class="linea" align="center" width="90%"><br>
        <div class="col-md-2 col-md-offset-1">
          <div class="titulo"><strong>EDUCATION:</strong></div>
        </div>
        <div class="col-md-4">
          <ul class="subtitulos">
            <ul class="subtitulos">
              <% @curriculum.educations.each do |education|%>
                <strong><%= education.institution %></strong><br>
                <p></p>
             <% end %>
            </ul>
          </ul>
        </div>
        <div class="col-md-4">
          <ul class="subtitulos">
            <ul class="subtitulos">
              <% @curriculum.educations.each do |education|%>
                <%= education.carreer %><br>
                <p></p>
             <% end %>
            </ul>
          </ul>
        </div>
      </div><br><br>
      <br>

      <div class="container final">
        <%= link_to 'Edit', edit_curriculum_path(@curriculum) %> |
        <%= link_to 'Back', curriculums_path %>
      </div>

      <div class="row footer">
        <div class="col-md-2 col-md-offset-1">
          <a class="logo" href="/home">
            <img class="cabecera" src="<%=image_path("small_timba.png")%>" alt="a clock">
          </a>
        </div>

        <div class="col-md-4">Exclusive access to top developers</div>
        <div class="col-md-3">Timba.co<br>Call us: 888.604.3188</div>
      </div>
    </section>
  </div>
  
  <br>
  <div class="container foot">
    <section class="section swatch-beige-black">
      <p>
        <a href="/curriculums" type="button" class="btn btn-primary btn-lg">To view more profiles</a>
      </p>
    </section>
  </div>
  <br><br>
</div>

app/views/cvs/_form.html.erb
<%= form_for(@cv) do |f| %>
  <% if @cv.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cv.errors.count, "error") %> prohibited this cv from being saved:</h2>

      <ul>
      <% @cv.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field name">
    <b><%= f.label :full_name %></b><br>
    <%= f.text_field :full_name %>
  </div><br>
  <div class="field profile">
    <b><%= f.label :profile %></b><br>
    <%= f.text_area :profile %>
  </div><br>
  <div class="field">
    <b><%= f.label :experience %>(years)</b><br>
    <%= f.number_field :experience %>
  </div><br>
  <div class="field experience">
    <b><%= f.label :recent_work_experience %></b><br>
    <%= f.text_area :recent_work_experience %>
  </div><br>
  <div class="field skills">
    <b><%= f.label :skills %></b><br>
    <%= f.text_area :skills %>
  </div><br>
  <div class="field education">
    <b><%= f.label :education %></b><br>
    <%= f.text_area :education %>
  </div><br>
  <div class="field">
   <b><%= f.label :languages %></b><br>
    <%= f.text_field :languages %>
  </div><br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cvs/edit.html.erb
<section class="section swatch-black-beige editing">
	<div class="container">
		<h1 class="headline hyper hairline">Editing cv</h1>

		<%= render 'form' %>
		<br>
		<%= link_to 'Show', @cv %> |
		<%= link_to 'Back', cvs_path %>
	</div>
</section>

app/views/cvs/index.html.erb
<section class="section swatch-black-beige adding">
  <div class="container">
    <h1 class="headline hyper hairline">CVS List</h1>

    <div class="add">
      <u><%= link_to 'New Add cv', new_cv_path %></u>
    </div><br>

    <table class="table table-striped">
      <thead>
        <tr>
          <th class="prim">Full Name</th>
          <th>Experience</th>
          <th>Recent work experience</th>
          <th>Skills</th>
          <th>Education</th>
          <th>Languages</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @cvs.each do |cv| %>
        <tr>
          <td><%= cv.full_name %></td>
          <td><%= cv.experience %></td>
          <td><%= cv.recent_work_experience %></td>
          <td><%= cv.skills %></td>
          <td><%= cv.education %></td>
          <td><%= cv.languages %></td>
          <p></p>
          <td><%= link_to 'Show', cv %></td>
          <td><%= link_to 'Edit', edit_cv_path(cv) %></td>
          <td><%= link_to 'Destroy', cv, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <br><br>
</section>

app/views/cvs/new.html.erb
<section class="section swatch-black-beige">
	<div class="container">
		<h1>New Cv</h1>

		<div class="form-group">
		    <label for="exampleInputFile">File input</label>
		    <input type="file" id="exampleInputFile">
		</div>

		<%= render 'form' %>

		<%= link_to 'Back', cvs_path %>
		<br><br><br><br><br><br>
	</div>
</section>

app/views/cvs/show.html.erb
<section class="section swatch-black-beige">
  <div class="container">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Full name:</strong><br>
      <%= @cv.full_name %>
    </p>

    <p>
      <strong>Profile:</strong><br>
      <%= @cv.profile %>
    </p>

    <p>
      <strong>Experience:</strong><br>
      <%= @cv.experience %>
    </p>

    <p>
      <strong>Recent work experience:</strong><br>
      <%= @cv.recent_work_experience %>
    </p>

    <p>
      <strong>Skills:</strong><br>
      <%= @cv.skills %>
    </p>

    <p>
      <strong>Education:</strong><br>
      <%= @cv.education %>
    </p>

    <p>
      <strong>Languages:</strong><br>
      <%= @cv.languages %>
    </p>

    <%= link_to 'Edit', edit_cv_path(@cv) %> |
    <%= link_to 'Back', cvs_path %>
  </div>
</section>